FROM openjdk:17-jdk-slim
WORKDIR /app
COPY target/jobfinder-0.0.1-SNAPSHOT.jar /app/jobfinder.jar
COPY src/main/resources/serviceAccountKey.json /app/serviceAccountKey.json
EXPOSE 8080
ENTRYPOINT ["java", "-jar", "jobfinder.jar", "--spring.profiles.active=docker"]
